name: Container Image Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  container-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t demo-app .

      # Step 4: Scan Docker image using Trivy
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.11.0
        with:
          image-ref: demo-app
          format: 'sarif'
          output: trivy-report.sarif

      # Step 5: Upload SARIF report as artifact
      - name: Upload SARIF report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-sarif-report
          path: trivy-report.sarif

      # Step 6: Upload SARIF report to GitHub Code Scanning
      - name: Upload SARIF report to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-report.sarif
