name: trivy

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "feature" ]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      security-events: write
      actions: read

    name: Build
    runs-on: "ubuntu-20.04"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'microsoft'
          cache: 'gradle'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make Gradlew executable
        run: chmod +x ./gradlew

      - name: Print Java version
        run: |
          java -version
          echo "JAVA_HOME=$JAVA_HOME"

      - name: Build with Gradle
        run: ./gradlew build --info

      - name: Build an image from Dockerfile
        run: docker build . -t vaishnavisonwanebnt/trivy_scanner

      - name: Log in to DockerHub
        run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin

      - name: Push the Docker image to DockerHub
        run: docker push vaishnavisonwanebnt/trivy_scanner:latest

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'vaishnavisonwanebnt/trivy_scanner:latest'  # Changed from 'app:latest'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'