name: trivy

on:
  push:
    branches: [ "master", "main" ]

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code [default]

    name: Container Image Scanning
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build the JAR file
        run: ./gradlew build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Push the Docker Image to GitHub Container Registry
        run: docker push ghcr.io/vaishnavisonwanebntsoft/trivy_scanner:latest
        
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}  # Use a Personal Access Token with appropriate permissions

      - name: Push the Docker Image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository_owner }}/trivy_scanner:latest

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'app:latest'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      # Compress the SARIF report into a ZIP file
      - name: Compress Trivy scan results into a ZIP file
        run: zip trivy-results.zip trivy-results.sarif

      # Upload the compressed ZIP file to GitHub Packages using the GitHub API
      - name: Upload to GitHub Packages
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/zip" \
            --data-binary @trivy-results.zip \
            "https://uploads.github.com/repos/${{ github.repository }}/packages/containers/container/trivy-results/versions/latest"